# Generated by Django 2.1.3 on 2018-11-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('image_url', models.ImageField(default='pics/none/no-img.jpg', upload_to='pics/')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
